version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@rails/actioncable"
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.3
  - dependency-name: "@rails/ujs"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@rails/activestorage"
    versions:
    - 6.1.1
    - 6.1.2
