inherit_from: .rubocop_todo.yml

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'bin/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/**/*'

Metrics/MethodLength:
  Exclude:
    - 'bin/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'bin/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/**/*'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/PerlBackrefs:
  Exclude:
    - 'bin/**/*'

Style/RedundantBegin:
  Exclude:
    - 'bin/**/*'
