version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: bundle install --jobs 4 --retry 3 --deployment && yarn install --check-files && bin/rails webpacker:compile test
