version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    allowed_updates:
      - match:
          update_type: "security"

