name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Set up for sqlite3 and webpacker
      run: sudo apt install -y libsqlite3-dev yarn
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Cache bundle
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundle-${{ hashFiles('Gemfile.lock') }}
    - name: Install dependencies (ruby)
      run: |
        bundle install --jobs 4 --retry 3 --deployment
    - name: Cache yarn
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
    - name: Install dependencies (js)
      run: yarn install --check-files
    - name: Build and test with Rake
      run: bin/rails webpacker:compile test
