name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Set up for sqlite3 and webpacker
      run: sudo apt install -y libsqlite3-dev yarn
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Build and test with Rake
      run: |
        set -x
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn install --check-files
        bin/rails webpacker:compile test
